apiVersion: v1
kind: Service
metadata:
  name: sage-app-service
spec:
  selector:
    app: sage-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Use NodePort if you're running locally on Minikube
