apiVersion: apps/v1
kind: Deployment
metadata:
  name: sage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sage
  template:
    metadata:
      labels:
        app: sage
    spec:
      containers:
        - name: sage
          image: okitamisan01/test-bot:latest # Use specific tag instead of 'latest' in production / 

          # # 1) Copy the image from your Mac (local Docker) into Minikube’s internal container runtime
          # minikube image load okitamisan01/test-bot:latest

          # # 2) Change the deployment’s imagePullPolicy to “IfNotPresent”
          # # (this prevents Kubernetes from trying to pull the image from Docker Hub every time)
          # kubectl patch deploy sage-deployment \
          #   -p '{"spec":{"template":{"spec":{"containers":[{"name":"sage","imagePullPolicy":"IfNotPresent"}]}}}}'

          # # 3) Restart the deployment to recreate the Pods
          # kubectl rollout restart deploy/sage-deployment

          # # 4) Watch the Pods as they start up
          # kubectl get pods -w

          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: sage-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: sage-config
                  key: LOG_LEVEL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: sage-secrets
                  key: API_KEY
