
apiVersion: v1
kind: Service
metadata:
  name: sage-service
spec:
  selector:
    app: sage  # Matches the labels in your deployment
  ports:
    - protocol: TCP
      port: 80       # External port to access the service
      targetPort: 8080  # Matches containerPort from deployment
  type: LoadBalancer  # Exposes the service externally (use NodePort for local clusters)