apiVersion: apps/v1
kind: Deployment
metadata:
  name: sage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sage
  template:
    metadata:
      labels:
        app: sage
    spec:
      containers:
      - name: sage
        image: danielmahler/sage-bot:latest  # Use specific tag instead of 'latest' in production
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"